version: "3.8"

services:
    mysql:
        image: mysql:8.0
        container_name: movies_db
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: movie_reviews
            MYSQL_USER: user
            MYSQL_PASSWORD: userpassword
        ports:
            - "3306:3306"
        volumes:
            - ./data:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - movie-network

networks:
    movie-network:
        external: true
